/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Asus
 */
public class CalendarCustom extends javax.swing.JPanel {
    private int month;
    private int year;
    /**
     * Creates new form CalendarCustom
     */
    public CalendarCustom() {
        initComponents();
        thisMonth();
        slide.show(new CalendarPanel(6, 2024), PanelSlide.AnimateType.TO_RIGHT);
        showMonthYear();
        myinit();
    }
    
    private void myinit(){
        prevBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (month == 1){
                    month = 12;
                    year--;
                }else{
                    month--;
                }
                slide.show(new CalendarPanel(month, year), PanelSlide.AnimateType.TO_RIGHT);
                showMonthYear();
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/prev_month_hover.png")));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/prev_month.png")));
            }
        });
        
        nextBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (month == 12){
                    month = 1;
                    year++;
                }else{
                    month++;
                }
                slide.show(new CalendarPanel(month, year), PanelSlide.AnimateType.TO_LEFT);
                showMonthYear();
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/next_month_hover.png")));
            }

            @Override
            public void mouseExited(MouseEvent e) {
               nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/next_month.png")));
            }
        });
    }
    
    private void thisMonth(){
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        month = calendar.get(Calendar.MONTH) +1;
        year = calendar.get(Calendar.YEAR);        
    }
    
    private void showMonthYear(){
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.MONTH, month-1);
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.DATE, 1);
        SimpleDateFormat date_format = new SimpleDateFormat("MMMM yyyy");
        month_year.setText(date_format.format(calendar.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slide = new App.PanelSlide();
        taskPanel = new javax.swing.JPanel();
        tasktxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        prevBtn = new javax.swing.JLabel();
        nextBtn = new javax.swing.JLabel();
        month_year = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 247, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 141, 189)));
        setPreferredSize(new java.awt.Dimension(1060, 535));
        setLayout(null);

        slide.setBackground(new java.awt.Color(255, 255, 255));
        slide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 141, 189)));
        slide.setPreferredSize(new java.awt.Dimension(784, 467));
        add(slide);
        slide.setBounds(0, 68, 780, 467);

        taskPanel.setBackground(new java.awt.Color(31, 139, 217));
        taskPanel.setPreferredSize(new java.awt.Dimension(280, 0));
        taskPanel.setLayout(null);

        tasktxt.setFont(new java.awt.Font("Montserrat SemiBold", 0, 32)); // NOI18N
        tasktxt.setForeground(new java.awt.Color(255, 255, 255));
        tasktxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tasktxt.setText("Tasks");
        tasktxt.setToolTipText("");
        taskPanel.add(tasktxt);
        tasktxt.setBounds(90, 20, 100, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/line.png"))); // NOI18N
        taskPanel.add(jLabel1);
        jLabel1.setBounds(30, 50, 232, 43);

        add(taskPanel);
        taskPanel.setBounds(780, -5, 280, 540);

        prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/prev_month.png"))); // NOI18N
        prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(prevBtn);
        prevBtn.setBounds(48, 26, 17, 21);

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/next_month.png"))); // NOI18N
        nextBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(nextBtn);
        nextBtn.setBounds(715, 26, 17, 21);

        month_year.setFont(new java.awt.Font("Montserrat SemiBold", 0, 28)); // NOI18N
        month_year.setForeground(new java.awt.Color(31, 139, 217));
        month_year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        month_year.setText("[month year]");
        month_year.setToolTipText("");
        add(month_year);
        month_year.setBounds(140, 15, 500, 35);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel month_year;
    private javax.swing.JLabel nextBtn;
    private javax.swing.JLabel prevBtn;
    private App.PanelSlide slide;
    private javax.swing.JPanel taskPanel;
    private javax.swing.JLabel tasktxt;
    // End of variables declaration//GEN-END:variables
}
