/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App;

import java.awt.Component;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Asus
 */
public class CalendarPanel extends javax.swing.JLayeredPane {
     private int month;
     private int year;
    /**
     * Creates new form CalendarPanel
     */
    public CalendarPanel(int month, int year) {
        initComponents();
        this.month = month;
        this.year = year;
        init();
    }
    
    private void init(){
        //set the titles style
        mon.asTitle();
        tue.asTitle();
        wed.asTitle();
        thu.asTitle();
        fri.asTitle();
        sat.asTitle();
        sun.asTitle();
        setDate();
    }
    
    private void setDate(){
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month-1);
        calendar.set(Calendar.DATE, 1);
        
        int start_day = calendar.get(Calendar.DAY_OF_WEEK) -1;
        calendar.add(Calendar.DATE, -start_day);
        CalendarToday today = getToday();
        
        for (Component comp : getComponents()){
            CalendarCell cell = (CalendarCell) comp;
            if (!cell.isTitle()){
                cell.setText(calendar.get(Calendar.DATE) + "");
                cell.setDate(calendar.getTime());
                cell.currentMonth(calendar.get(Calendar.MONTH) == month -1, calendar.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY);
                
                if (today.isToday(new CalendarToday(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH), calendar.get(Calendar.YEAR)))){
                    cell.setAsToday();
                }
                calendar.add(Calendar.DATE, 1);
            }
        }
    }
    
    private CalendarToday getToday(){
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        return new CalendarToday(cal.get(Calendar.DATE), cal.get(Calendar.MONTH), cal.get(Calendar.YEAR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sun = new App.CalendarCell();
        mon = new App.CalendarCell();
        tue = new App.CalendarCell();
        wed = new App.CalendarCell();
        thu = new App.CalendarCell();
        fri = new App.CalendarCell();
        sat = new App.CalendarCell();
        calendarCell8 = new App.CalendarCell();
        calendarCell9 = new App.CalendarCell();
        calendarCell10 = new App.CalendarCell();
        calendarCell11 = new App.CalendarCell();
        calendarCell12 = new App.CalendarCell();
        calendarCell13 = new App.CalendarCell();
        calendarCell14 = new App.CalendarCell();
        calendarCell15 = new App.CalendarCell();
        calendarCell16 = new App.CalendarCell();
        calendarCell17 = new App.CalendarCell();
        calendarCell18 = new App.CalendarCell();
        calendarCell19 = new App.CalendarCell();
        calendarCell20 = new App.CalendarCell();
        calendarCell21 = new App.CalendarCell();
        calendarCell22 = new App.CalendarCell();
        calendarCell23 = new App.CalendarCell();
        calendarCell24 = new App.CalendarCell();
        calendarCell25 = new App.CalendarCell();
        calendarCell26 = new App.CalendarCell();
        calendarCell27 = new App.CalendarCell();
        calendarCell28 = new App.CalendarCell();
        calendarCell29 = new App.CalendarCell();
        calendarCell30 = new App.CalendarCell();
        calendarCell31 = new App.CalendarCell();
        calendarCell32 = new App.CalendarCell();
        calendarCell33 = new App.CalendarCell();
        calendarCell34 = new App.CalendarCell();
        calendarCell35 = new App.CalendarCell();
        calendarCell36 = new App.CalendarCell();
        calendarCell37 = new App.CalendarCell();
        calendarCell38 = new App.CalendarCell();
        calendarCell39 = new App.CalendarCell();
        calendarCell40 = new App.CalendarCell();
        calendarCell41 = new App.CalendarCell();
        calendarCell42 = new App.CalendarCell();
        calendarCell43 = new App.CalendarCell();
        calendarCell44 = new App.CalendarCell();
        calendarCell45 = new App.CalendarCell();
        calendarCell46 = new App.CalendarCell();
        calendarCell47 = new App.CalendarCell();
        calendarCell48 = new App.CalendarCell();
        calendarCell49 = new App.CalendarCell();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(784, 467));
        setLayout(new java.awt.GridLayout(7, 7));

        sun.setBackground(new java.awt.Color(255, 255, 255));
        sun.setForeground(new java.awt.Color(234, 111, 111));
        sun.setText("Sun");
        sun.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        sun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunActionPerformed(evt);
            }
        });
        add(sun);

        mon.setBackground(new java.awt.Color(255, 255, 255));
        mon.setForeground(new java.awt.Color(0, 141, 189));
        mon.setText("Mon");
        mon.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        add(mon);

        tue.setBackground(new java.awt.Color(255, 255, 255));
        tue.setForeground(new java.awt.Color(0, 141, 189));
        tue.setText("Tue");
        tue.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        tue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tueActionPerformed(evt);
            }
        });
        add(tue);

        wed.setBackground(new java.awt.Color(255, 255, 255));
        wed.setForeground(new java.awt.Color(0, 141, 189));
        wed.setText("Wed");
        wed.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        wed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wedActionPerformed(evt);
            }
        });
        add(wed);

        thu.setBackground(new java.awt.Color(255, 255, 255));
        thu.setForeground(new java.awt.Color(0, 141, 189));
        thu.setText("Thu");
        thu.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        thu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuActionPerformed(evt);
            }
        });
        add(thu);

        fri.setBackground(new java.awt.Color(255, 255, 255));
        fri.setForeground(new java.awt.Color(0, 141, 189));
        fri.setText("Fri");
        fri.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        fri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friActionPerformed(evt);
            }
        });
        add(fri);

        sat.setBackground(new java.awt.Color(255, 255, 255));
        sat.setForeground(new java.awt.Color(0, 141, 189));
        sat.setText("Sat");
        sat.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        sat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satActionPerformed(evt);
            }
        });
        add(sat);

        calendarCell8.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell8.setForeground(new java.awt.Color(234, 111, 111));
        calendarCell8.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell8ActionPerformed(evt);
            }
        });
        add(calendarCell8);

        calendarCell9.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell9.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell9ActionPerformed(evt);
            }
        });
        add(calendarCell9);

        calendarCell10.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell10.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell10ActionPerformed(evt);
            }
        });
        add(calendarCell10);

        calendarCell11.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell11.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell11ActionPerformed(evt);
            }
        });
        add(calendarCell11);

        calendarCell12.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell12.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell12ActionPerformed(evt);
            }
        });
        add(calendarCell12);

        calendarCell13.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell13.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell13ActionPerformed(evt);
            }
        });
        add(calendarCell13);

        calendarCell14.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell14.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell14ActionPerformed(evt);
            }
        });
        add(calendarCell14);

        calendarCell15.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell15.setForeground(new java.awt.Color(234, 111, 111));
        calendarCell15.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell15ActionPerformed(evt);
            }
        });
        add(calendarCell15);

        calendarCell16.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell16.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell16ActionPerformed(evt);
            }
        });
        add(calendarCell16);

        calendarCell17.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell17.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell17ActionPerformed(evt);
            }
        });
        add(calendarCell17);

        calendarCell18.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell18.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell18ActionPerformed(evt);
            }
        });
        add(calendarCell18);

        calendarCell19.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell19.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell19ActionPerformed(evt);
            }
        });
        add(calendarCell19);

        calendarCell20.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell20.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell20ActionPerformed(evt);
            }
        });
        add(calendarCell20);

        calendarCell21.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell21.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell21ActionPerformed(evt);
            }
        });
        add(calendarCell21);

        calendarCell22.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell22.setForeground(new java.awt.Color(234, 111, 111));
        calendarCell22.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell22ActionPerformed(evt);
            }
        });
        add(calendarCell22);

        calendarCell23.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell23.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell23ActionPerformed(evt);
            }
        });
        add(calendarCell23);

        calendarCell24.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell24.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell24ActionPerformed(evt);
            }
        });
        add(calendarCell24);

        calendarCell25.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell25.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell25ActionPerformed(evt);
            }
        });
        add(calendarCell25);

        calendarCell26.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell26.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell26ActionPerformed(evt);
            }
        });
        add(calendarCell26);

        calendarCell27.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell27.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell27ActionPerformed(evt);
            }
        });
        add(calendarCell27);

        calendarCell28.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell28.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell28ActionPerformed(evt);
            }
        });
        add(calendarCell28);

        calendarCell29.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell29.setForeground(new java.awt.Color(234, 111, 111));
        calendarCell29.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell29ActionPerformed(evt);
            }
        });
        add(calendarCell29);

        calendarCell30.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell30.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell30ActionPerformed(evt);
            }
        });
        add(calendarCell30);

        calendarCell31.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell31.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell31ActionPerformed(evt);
            }
        });
        add(calendarCell31);

        calendarCell32.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell32.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell32ActionPerformed(evt);
            }
        });
        add(calendarCell32);

        calendarCell33.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell33.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell33ActionPerformed(evt);
            }
        });
        add(calendarCell33);

        calendarCell34.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell34.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell34ActionPerformed(evt);
            }
        });
        add(calendarCell34);

        calendarCell35.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell35.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell35ActionPerformed(evt);
            }
        });
        add(calendarCell35);

        calendarCell36.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell36.setForeground(new java.awt.Color(234, 111, 111));
        calendarCell36.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell36ActionPerformed(evt);
            }
        });
        add(calendarCell36);

        calendarCell37.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell37.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell37ActionPerformed(evt);
            }
        });
        add(calendarCell37);

        calendarCell38.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell38.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell38ActionPerformed(evt);
            }
        });
        add(calendarCell38);

        calendarCell39.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell39.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell39ActionPerformed(evt);
            }
        });
        add(calendarCell39);

        calendarCell40.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell40.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell40ActionPerformed(evt);
            }
        });
        add(calendarCell40);

        calendarCell41.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell41.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell41ActionPerformed(evt);
            }
        });
        add(calendarCell41);

        calendarCell42.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell42.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell42ActionPerformed(evt);
            }
        });
        add(calendarCell42);

        calendarCell43.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell43.setForeground(new java.awt.Color(234, 111, 111));
        calendarCell43.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell43ActionPerformed(evt);
            }
        });
        add(calendarCell43);

        calendarCell44.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell44.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell44ActionPerformed(evt);
            }
        });
        add(calendarCell44);

        calendarCell45.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell45.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell45ActionPerformed(evt);
            }
        });
        add(calendarCell45);

        calendarCell46.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell46.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell46ActionPerformed(evt);
            }
        });
        add(calendarCell46);

        calendarCell47.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell47.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell47ActionPerformed(evt);
            }
        });
        add(calendarCell47);

        calendarCell48.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell48.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell48ActionPerformed(evt);
            }
        });
        add(calendarCell48);

        calendarCell49.setBackground(new java.awt.Color(255, 255, 255));
        calendarCell49.setFont(new java.awt.Font("Montserrat", 0, 22)); // NOI18N
        calendarCell49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarCell49ActionPerformed(evt);
            }
        });
        add(calendarCell49);
    }// </editor-fold>//GEN-END:initComponents

    private void sunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    private void tueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tueActionPerformed

    private void wedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wedActionPerformed

    private void thuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thuActionPerformed

    private void friActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friActionPerformed

    private void satActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satActionPerformed

    private void calendarCell8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell8ActionPerformed

    private void calendarCell9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell9ActionPerformed

    private void calendarCell10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell10ActionPerformed

    private void calendarCell11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell11ActionPerformed

    private void calendarCell12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell12ActionPerformed

    private void calendarCell13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell13ActionPerformed

    private void calendarCell14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell14ActionPerformed

    private void calendarCell15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell15ActionPerformed

    private void calendarCell16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell16ActionPerformed

    private void calendarCell17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell17ActionPerformed

    private void calendarCell18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell18ActionPerformed

    private void calendarCell19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell19ActionPerformed

    private void calendarCell20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell20ActionPerformed

    private void calendarCell21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell21ActionPerformed

    private void calendarCell22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell22ActionPerformed

    private void calendarCell23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell23ActionPerformed

    private void calendarCell24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell24ActionPerformed

    private void calendarCell25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell25ActionPerformed

    private void calendarCell26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell26ActionPerformed

    private void calendarCell27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell27ActionPerformed

    private void calendarCell28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell28ActionPerformed

    private void calendarCell29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell29ActionPerformed

    private void calendarCell30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell30ActionPerformed

    private void calendarCell31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell31ActionPerformed

    private void calendarCell32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell32ActionPerformed

    private void calendarCell33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell33ActionPerformed

    private void calendarCell34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell34ActionPerformed

    private void calendarCell35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell35ActionPerformed

    private void calendarCell36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell36ActionPerformed

    private void calendarCell37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell37ActionPerformed

    private void calendarCell38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell38ActionPerformed

    private void calendarCell39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell39ActionPerformed

    private void calendarCell40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell40ActionPerformed

    private void calendarCell41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell41ActionPerformed

    private void calendarCell42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell42ActionPerformed

    private void calendarCell43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell43ActionPerformed

    private void calendarCell44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell44ActionPerformed

    private void calendarCell45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell45ActionPerformed

    private void calendarCell46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell46ActionPerformed

    private void calendarCell47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell47ActionPerformed

    private void calendarCell48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell48ActionPerformed

    private void calendarCell49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarCell49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarCell49ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private App.CalendarCell calendarCell10;
    private App.CalendarCell calendarCell11;
    private App.CalendarCell calendarCell12;
    private App.CalendarCell calendarCell13;
    private App.CalendarCell calendarCell14;
    private App.CalendarCell calendarCell15;
    private App.CalendarCell calendarCell16;
    private App.CalendarCell calendarCell17;
    private App.CalendarCell calendarCell18;
    private App.CalendarCell calendarCell19;
    private App.CalendarCell calendarCell20;
    private App.CalendarCell calendarCell21;
    private App.CalendarCell calendarCell22;
    private App.CalendarCell calendarCell23;
    private App.CalendarCell calendarCell24;
    private App.CalendarCell calendarCell25;
    private App.CalendarCell calendarCell26;
    private App.CalendarCell calendarCell27;
    private App.CalendarCell calendarCell28;
    private App.CalendarCell calendarCell29;
    private App.CalendarCell calendarCell30;
    private App.CalendarCell calendarCell31;
    private App.CalendarCell calendarCell32;
    private App.CalendarCell calendarCell33;
    private App.CalendarCell calendarCell34;
    private App.CalendarCell calendarCell35;
    private App.CalendarCell calendarCell36;
    private App.CalendarCell calendarCell37;
    private App.CalendarCell calendarCell38;
    private App.CalendarCell calendarCell39;
    private App.CalendarCell calendarCell40;
    private App.CalendarCell calendarCell41;
    private App.CalendarCell calendarCell42;
    private App.CalendarCell calendarCell43;
    private App.CalendarCell calendarCell44;
    private App.CalendarCell calendarCell45;
    private App.CalendarCell calendarCell46;
    private App.CalendarCell calendarCell47;
    private App.CalendarCell calendarCell48;
    private App.CalendarCell calendarCell49;
    private App.CalendarCell calendarCell8;
    private App.CalendarCell calendarCell9;
    private App.CalendarCell fri;
    private App.CalendarCell mon;
    private App.CalendarCell sat;
    private App.CalendarCell sun;
    private App.CalendarCell thu;
    private App.CalendarCell tue;
    private App.CalendarCell wed;
    // End of variables declaration//GEN-END:variables
}
