/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Asus
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Signup() {
        initComponents();
        myinit();
    }
    
    private void setBottomBorder(javax.swing.JTextField field){
        Border bottomBorder = BorderFactory.createMatteBorder(0,0,1,0, Color.BLACK);
        field.setBorder(bottomBorder);
        field.setOpaque(false);
        field.setBackground(new java.awt.Color(0,0,0,0));
    }
    
    private void myinit(){
        //style the username textfield to has transparent background and only bottom border 
        setBottomBorder(username_field);
        setBottomBorder(password_field);
        setBottomBorder(confirm_field);
        
        
        //set the hover and click action for signup button
        loginBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setVisible(false);
                new Login().setVisible(true);
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/hover_smallButton.png")));
                logintxt.setForeground(new java.awt.Color(252, 239, 220));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/smallButton.png")));      
                logintxt.setForeground(new java.awt.Color(112, 79, 40));
            }
        });
        
        //set the click action for hide and show password
        show_pass.addMouseListener(new MouseAdapter() {
            boolean showPass = false;

            @Override
            public void mouseClicked(MouseEvent e) {
                if (!showPass){
                    show_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/hide_password.png")));
                    showPass = true;
                }else{
                    show_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/show_password.png")));
                    showPass = false;
                }
            }
        });
        
        show_conf.addMouseListener(new MouseAdapter() {
            boolean showConf = false;

            @Override
            public void mouseClicked(MouseEvent e) {
                if (!showConf){
                    show_conf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/hide_password.png")));
                    showConf = true;
                }else{
                    show_conf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/show_password.png")));
                    showConf = false;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alr_have_txt = new javax.swing.JLabel();
        logintxt = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        show_pass = new javax.swing.JLabel();
        show_conf = new javax.swing.JLabel();
        confirmtxt = new javax.swing.JLabel();
        confirm_field = new javax.swing.JPasswordField();
        passwordtxt = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        username_field = new javax.swing.JTextField();
        usernametxt = new javax.swing.JLabel();
        backBtn = new App.ButtonCustom();
        submitBtn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alr_have_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 20)); // NOI18N
        alr_have_txt.setText("<html><u>Already have an account?</u></html>");
        alr_have_txt.setToolTipText("");
        getContentPane().add(alr_have_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 499, -1, -1));

        logintxt.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        logintxt.setForeground(new java.awt.Color(112, 79, 40));
        logintxt.setText("Login");
        logintxt.setToolTipText("");
        getContentPane().add(logintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 499, -1, -1));

        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/smallButton.png"))); // NOI18N
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 490, -1, -1));

        show_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/show_password.png"))); // NOI18N
        getContentPane().add(show_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 410, -1, -1));

        show_conf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/show_password.png"))); // NOI18N
        getContentPane().add(show_conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 310, -1, -1));

        confirmtxt.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        confirmtxt.setText("Confirm Password");
        getContentPane().add(confirmtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 363, -1, -1));

        confirm_field.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        confirm_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(confirm_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 399, 556, 42));

        passwordtxt.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        passwordtxt.setText("Password");
        getContentPane().add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 266, -1, -1));

        password_field.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 302, 556, 42));

        username_field.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        username_field.setToolTipText("");
        getContentPane().add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 198, 556, 42));

        usernametxt.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        usernametxt.setText("Username");
        getContentPane().add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 165, -1, -1));

        backBtn.setBackground(new java.awt.Color(245, 215, 180));
        backBtn.setForeground(new java.awt.Color(184, 138, 82));
        backBtn.setText("< Back");
        backBtn.setBorderColor(new java.awt.Color(245, 215, 180));
        backBtn.setBorderColorNotOver(new java.awt.Color(245, 215, 180));
        backBtn.setBorderColorOver(new java.awt.Color(238, 202, 158));
        backBtn.setColor(new java.awt.Color(245, 215, 180));
        backBtn.setColor2(new java.awt.Color(184, 138, 82));
        backBtn.setColorClick(new java.awt.Color(238, 202, 158));
        backBtn.setColorClick2(new java.awt.Color(204, 162, 109));
        backBtn.setColorOver(new java.awt.Color(238, 202, 158));
        backBtn.setColorOver2(new java.awt.Color(204, 162, 109));
        backBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 32)); // NOI18N
        backBtn.setPreferredSize(new java.awt.Dimension(161, 69));
        backBtn.setRadius(40);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 161, 69));

        submitBtn.setBackground(new java.awt.Color(112, 79, 40));
        submitBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 30)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 590, 242, 59));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/Signup.png"))); // NOI18N
        bg.setText("jLabel1");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new WelcomePage().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void confirm_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_fieldActionPerformed

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alr_have_txt;
    private App.ButtonCustom backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JPasswordField confirm_field;
    private javax.swing.JLabel confirmtxt;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel logintxt;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel passwordtxt;
    private javax.swing.JLabel show_conf;
    private javax.swing.JLabel show_pass;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel usernametxt;
    // End of variables declaration//GEN-END:variables
}
